<?php

namespace Roots\BedrockCli\Services;

use Symfony\Component\Console\Output\OutputInterface;

class PluginDependencyManager
{
    public function resolvePluginDependencies(string $projectPath, OutputInterface $output): void
    {
        $pluginsDir = $projectPath . '/web/app/plugins';
        if (!is_dir($pluginsDir)) {
            return;
        }

        $projectDependencies = $this->getProjectDependencies($projectPath);
        $plugins = array_filter(scandir($pluginsDir), function($item) use ($pluginsDir) {
            return $item !== '.' && $item !== '..' && is_dir($pluginsDir . '/' . $item);
        });

        foreach ($plugins as $plugin) {
            $pluginPath = $pluginsDir . '/' . $plugin;
            $this->processPlugin($pluginPath, $projectDependencies, $output);
        }
    }

    private function processPlugin(string $pluginPath, array $projectDependencies, OutputInterface $output): void
    {
        $composerFile = $pluginPath . '/composer.json';
        if (!file_exists($composerFile)) {
            return;
        }

        $pluginComposer = json_decode(file_get_contents($composerFile), true);
        $pluginDeps = $pluginComposer['require'] ?? [];

        if (empty($pluginDeps)) {
            return;
        }

        $pluginName = basename($pluginPath);
        
        if ($this->areDependenciesSatisfied($pluginDeps, $projectDependencies)) {
            $this->createStubAutoloader($pluginPath, $pluginName, $output);
        } else {
            $output->writeln("<comment>⚠️  Plugin {$pluginName} necesita dependencias locales</comment>");
        }
    }

    private function areDependenciesSatisfied(array $pluginDeps, array $projectDeps): bool
    {
        foreach ($pluginDeps as $package => $version) {
            if (!isset($projectDeps[$package])) {
                return false;
            }
            
            // Verificación básica de versión compatible
            if (!$this->isVersionCompatible($version, $projectDeps[$package])) {
                return false;
            }
        }
        
        return true;
    }

    private function isVersionCompatible(string $required, string $installed): bool
    {
        // Simplificado: si es dev o tiene ^, asumir compatible
        if (str_contains($required, 'dev') || str_contains($required, '^') || str_contains($required, '*')) {
            return true;
        }
        
        return version_compare($installed, $required, '>=');
    }

    private function createStubAutoloader(string $pluginPath, string $pluginName, OutputInterface $output): void
    {
        $vendorDir = $pluginPath . '/vendor';
        if (!is_dir($vendorDir)) {
            mkdir($vendorDir, 0755, true);
        }

        $stubContent = "<?php\n// Dependencies satisfied by project-level autoloader\n// Generated by bedrock-cli PluginDependencyManager\nreturn;\n";
        file_put_contents($vendorDir . '/autoload.php', $stubContent);
        
        $output->writeln("<info>✓ Stub autoloader creado para {$pluginName}</info>");
    }

    private function getProjectDependencies(string $projectPath): array
    {
        $composerLock = $projectPath . '/composer.lock';
        if (!file_exists($composerLock)) {
            return [];
        }

        $lockData = json_decode(file_get_contents($composerLock), true);
        $dependencies = [];

        foreach ($lockData['packages'] ?? [] as $package) {
            $dependencies[$package['name']] = $package['version'];
        }

        return $dependencies;
    }
}